### ISSUE TITLE
https support?

### ISSUE THREAD

**Issue by edankwan** [wearekuva/wearekuva.github.io#1]
WebVR will likely require HTTPS protocol when it releases.

https://lists.w3.org/Archives/Public/public-webvr/2016Jul/0000.html

**Comment by marklundin** [comment]
Yay, we're now https! https://wearekuva.com/

**Comment by marklundin** [comment]
http://wearekuva.com, http://www.wearekuva.com and https://www.wearekuva.com should all now redirect to https://wearekuva.com
